import { NextRequest,NextResponse } from 'next/server';
import { and,eq } from 'drizzle-orm';
import { requireUser } from '@/lib/auth';
import { assertSameOrigin } from '@/lib/http';
import { db,ensureSchema } from '@/lib/db';
import { catalogs } from '@/lib/schema';
import { userPlan } from '@/lib/accounts';
import { validateSlug } from '@/lib/slug';
import { pdfStreamFromRequest } from '@/lib/upload';
import { deleteCatalogFiles,generateCatalogFiles,regenerateCatalogWeb,sourceFilename } from '@/lib/storage';
import { renderSettingsForCatalog,renderSettingsFromSearchParams } from '@/lib/render-settings';
import { parseStaticNavigationMode,parseStaticPdf } from '@/lib/navigation';
export const maxDuration=300;
async function owned(userId:string,id:string){await ensureSchema();const [catalog]=await db().select().from(catalogs).where(and(eq(catalogs.id,id),eq(catalogs.userId,userId))).limit(1);return catalog||null;}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{assertSameOrigin(request);const user=await requireUser();const {id}=await params;const current=await owned(user.id,id);if(!current)return NextResponse.json({error:'NOT_FOUND'},{status:404});const plan=await userPlan(user.id);if(!plan)return NextResponse.json({error:'PLAN_MISSING'},{status:403});const title=(request.nextUrl.searchParams.get('title')||'').trim();if(!title)return NextResponse.json({error:'TITLE_REQUIRED'},{status:400});const requested=(request.nextUrl.searchParams.get('slug')||'').trim();let slug=current.slug;if(plan.customSlug&&requested)slug=validateSlug(requested);const [dup]=await db().select({id:catalogs.id}).from(catalogs).where(eq(catalogs.slug,slug)).limit(1);if(dup&&dup.id!==id)return NextResponse.json({error:'SLUG_EXISTS'},{status:409});const staticPdf=parseStaticPdf(request.nextUrl.searchParams.get('staticPdf'),current.staticPdf);const navigationMode=parseStaticNavigationMode(request.nextUrl.searchParams.get('navigationMode'),current.navigationMode as any);const settings=renderSettingsFromSearchParams(request.nextUrl.searchParams,renderSettingsForCatalog(current));const regenerate=request.nextUrl.searchParams.get('regenerate')==='true';const progressJob=request.nextUrl.searchParams.get('progressJob')||undefined;const pdf=await pdfStreamFromRequest(request,false);let originalFilename=current.originalFilename,fileSize=current.fileSize,objectKey=current.objectKey,pageCount=current.generatedPageCount,linkCount=current.generatedLinkCount,generatedSize=current.generatedSize,generatedAt=current.generatedAt,didGenerate=false;if(pdf){const manifest=await generateCatalogFiles(id,pdf.stream,pdf.size,settings,progressJob);originalFilename=pdf.filename;fileSize=pdf.size;objectKey=sourceFilename(id);pageCount=manifest.pageCount;linkCount=manifest.linkCount;generatedSize=manifest.generatedImageBytes||0;generatedAt=new Date();didGenerate=true;}else if(regenerate){const manifest=await regenerateCatalogWeb(id,settings,progressJob);pageCount=manifest.pageCount;linkCount=manifest.linkCount;generatedSize=manifest.generatedImageBytes||0;generatedAt=new Date();didGenerate=true;}await db().update(catalogs).set({title,slug,active:request.nextUrl.searchParams.get('active')!=='false',staticPdf,navigationMode,objectKey,originalFilename,fileSize,renderDpi:didGenerate?settings.renderDpi:current.renderDpi,webpQuality:didGenerate?settings.webpQuality:current.webpQuality,webpLossless:didGenerate?settings.webpLossless:current.webpLossless,generatedPageCount:pageCount,generatedLinkCount:linkCount,generatedSize,generatedAt,updatedAt:new Date()}).where(eq(catalogs.id,id));return NextResponse.json({ok:true,slug,regenerated:didGenerate});}catch(e){const m=e instanceof Error?e.message:'UPDATE_FAILED';console.error(e);return NextResponse.json({error:m},{status:m==='RENDER_SETTINGS_INVALID'||m==='NAVIGATION_MODE_INVALID'||m.includes('نامک')?400:500});}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{assertSameOrigin(request);const user=await requireUser();const {id}=await params;const current=await owned(user.id,id);if(!current)return NextResponse.json({error:'NOT_FOUND'},{status:404});await db().delete(catalogs).where(eq(catalogs.id,id));await deleteCatalogFiles(id);return NextResponse.json({ok:true});}catch(e){console.error(e);return NextResponse.json({error:'DELETE_FAILED'},{status:500});}}
