import { redirect } from 'next/navigation';
import { desc,eq } from 'drizzle-orm';
import { currentUser } from '@/lib/auth';
import { currentLocale } from '@/lib/i18n';
import { db,ensureSchema } from '@/lib/db';
import { catalogs } from '@/lib/schema';
import { userPlan,userStorageUsed } from '@/lib/accounts';
import { defaultRenderSettings } from '@/lib/render-settings';
import { parseStaticNavigationMode } from '@/lib/navigation';
import { env } from '@/lib/env';
import AccountLogin from '@/components/AccountLogin';
import UserCatalogManager from '@/components/UserCatalogManager';
function bytes(n:number){return n<1024*1024?`${Math.round(n/1024)} KB`:`${(n/1024/1024).toFixed(1)} MB`;}
export const dynamic='force-dynamic';
export default async function AccountPage(){const locale=await currentLocale();const fa=locale==='fa';const user=await currentUser();if(!user)return <AccountLogin locale={locale}/>;await ensureSchema();const plan=await userPlan(user.id);if(!plan)redirect('/');const used=await userStorageUsed(user.id);const rows=await db().select().from(catalogs).where(eq(catalogs.userId,user.id)).orderBy(desc(catalogs.createdAt));const items=rows.map(c=>({...c,navigationMode:parseStaticNavigationMode(c.navigationMode),generatedAt:c.generatedAt?.toISOString()||null,createdAt:c.createdAt.toISOString(),updatedAt:c.updatedAt.toISOString()}));return <div className="accountShell"><header className="accountHeader"><div className="container accountHeaderInner"><a className="brand" href="/"><span><strong>Publio</strong><small>POWERED BY BADJE.IR</small></span></a><div className="accountHeaderActions"><a className="btn btnSoft" href={`/api/locale?lang=${fa?'en':'fa'}&next=/account`}>{fa?'English':'فارسی'}</a><form action="/api/auth/logout" method="post"><button className="btn btnGhost">{fa?'خروج':'Sign out'}</button></form></div></div></header><main className="container adminMain"><div className="adminIntro"><div><div className="eyebrow">PUBLIO</div><h1>{fa?'فضای کار شما':'Your workspace'}</h1><p dir="ltr">{user.email}</p></div></div>{user.status==='suspended'?<div className="alertError">{fa?'حساب شما تعلیق شده است.':'Your account is suspended.'}</div>:<><div className="statsRow"><article><span>{fa?'پلن':'Plan'}</span><strong>{fa?plan.nameFa:plan.nameEn}</strong></article><article><span>{fa?'فضای مصرف‌شده':'Storage used'}</span><strong>{bytes(used)} / {bytes(plan.storageLimitBytes)}</strong></article><article><span>{fa?'لینک اختصاصی':'Custom link'}</span><strong>{plan.customSlug?(fa?'فعال':'Enabled'):(fa?'نیاز به ارتقا':'Upgrade')}</strong></article></div><section className="upgradeCard"><div><h2>{fa?'برای برند خود لینک اختصاصی می‌خواهید؟':'Want a branded custom link?'}</h2><p>{fa?'پلن رایگان برای شروع ۵۰ مگابایت فضا دارد و لینک‌ها را به‌صورت تصادفی می‌سازد. برای فضای بیشتر یا لینک دلخواه، با ما تماس بگیرید.':'The free plan includes 50 MB and generates random links. Contact us for more storage or a custom catalog URL.'}</p></div><a className="btn" href="mailto:publio@badje.ir">{fa?'ارتقای پلن':'Upgrade plan'}</a></section><UserCatalogManager locale={locale} customSlug={plan.customSlug} maxUploadMb={env().MAX_UPLOAD_MB} items={items} defaults={defaultRenderSettings()}/></>}</main></div>}
