import { redirect } from 'next/navigation';
import { eq, desc } from 'drizzle-orm';
import { currentUser } from '@/lib/auth';
import { currentLocale } from '@/lib/i18n';
import { db, ensureSchema } from '@/lib/db';
import { catalogs } from '@/lib/schema';
import { userPlan, userStorageUsed } from '@/lib/accounts';
import AccountLogin from '@/components/AccountLogin';
import UserCatalogUploader from '@/components/UserCatalogUploader';
function bytes(n:number){return n<1024*1024?`${Math.round(n/1024)} KB`:`${(n/1024/1024).toFixed(1)} MB`;}
export const dynamic='force-dynamic';
export default async function AccountPage(){const locale=await currentLocale();const fa=locale==='fa';const user=await currentUser();if(!user)return <AccountLogin locale={locale}/>;await ensureSchema();const plan=await userPlan(user.id);if(!plan)redirect('/');const used=await userStorageUsed(user.id);const rows=await db().select().from(catalogs).where(eq(catalogs.userId,user.id)).orderBy(desc(catalogs.createdAt));return <main className="container adminMain"><div className="adminIntro"><div><div className="eyebrow">PUBLIO</div><h1>{fa?'حساب کاربری':'Your account'}</h1><p dir="ltr">{user.email}</p></div><div className="heroActions"><a className="btn btnSoft" href={`/api/locale?lang=${fa?'en':'fa'}&next=/account`}>{fa?'English':'فارسی'}</a><form action="/api/auth/logout" method="post"><button className="btn btnGhost">{fa?'خروج':'Sign out'}</button></form></div></div>{user.status==='suspended'?<div className="alertError">{fa?'حساب شما تعلیق شده است.':'Your account is suspended.'}</div>:<><div className="statsRow"><article><span>{fa?'پلن':'Plan'}</span><strong>{fa?plan.nameFa:plan.nameEn}</strong></article><article><span>{fa?'فضای مصرف‌شده':'Storage used'}</span><strong>{bytes(used)} / {bytes(plan.storageLimitBytes)}</strong></article><article><span>{fa?'لینک اختصاصی':'Custom link'}</span><strong>{plan.customSlug?(fa?'فعال':'Enabled'):(fa?'پلن پولی':'Paid plan')}</strong></article></div><p><a href="mailto:publio@badje.ir">{fa?'برای فضای بیشتر یا لینک اختصاصی با ما تماس بگیرید.':'Need more storage or a custom link? Contact us.'}</a></p><UserCatalogUploader locale={locale} customSlug={plan.customSlug}/><section className="section"><div className="sectionHeading"><h2>{fa?'کاتالوگ‌های شما':'Your catalogs'}</h2></div><div className="catalogTable">{rows.map(c=><div className="catalogRow" key={c.id}><div className="catalogName"><div><strong>{c.title}</strong><small>/{c.slug}</small></div></div><div className="catalogLink"><a href={`/${c.slug}`} target="_blank">/{c.slug}</a></div><div><span className="status active">{bytes(c.fileSize+c.generatedSize)}</span></div></div>)}</div></section></>}</main>}
