'use client';
import { useState } from 'react';
import type { Locale } from '@/lib/i18n';

export default function AccountLogin({locale}:{locale:Locale}){
  const fa=locale==='fa'; const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [step,setStep]=useState<'email'|'otp'>('email'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function requestOtp(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/auth/request-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,locale})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error==='SUSPENDED'?(fa?'حساب شما تعلیق شده است.':'Your account is suspended.'):(fa?'ارسال کد انجام نشد.':'Could not send the code.'));return;}setStep('otp');}
  async function verify(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/auth/verify-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,code,locale})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error==='SUSPENDED'?(fa?'حساب شما تعلیق شده است.':'Your account is suspended.'):(fa?'کد واردشده معتبر نیست.':'The code is invalid or expired.'));return;}location.href='/account';}
  return <main className="authPage"><section className="authVisual"><a className="brand lightBrand" href="/"><span><strong>Publio</strong><small>Powered by badje.ir</small></span></a><div className="authPitch"><div className="eyebrow light">{fa?'حساب کاربری':'PUBLIO ACCOUNT'}</div><h1>{fa?'ثبت‌نام و ورود با ایمیل':'Sign in or register with email'}</h1><p>{fa?'بدون رمز عبور؛ یک کد یک‌بارمصرف برای شما ایمیل می‌کنیم.':'No password. We will email you a one-time verification code.'}</p></div></section><section className="authFormWrap"><form className="authForm" onSubmit={step==='email'?requestOtp:verify}><div className="formHeading"><h2>{step==='email'?(fa?'ورود / ثبت‌نام':'Sign in / Register'):(fa?'کد تأیید':'Verification code')}</h2><p>{step==='email'?(fa?'ایمیل خود را وارد کنید.':'Enter your email address.'):(fa?`کد ارسال‌شده به ${email} را وارد کنید.`:`Enter the code sent to ${email}.`)}</p></div>{error&&<div className="alertError">{error}</div>}{step==='email'?<label className="field"><span>{fa?'ایمیل':'Email'}</span><input type="email" required autoFocus value={email} onChange={e=>setEmail(e.target.value)} dir="ltr"/></label>:<label className="field"><span>{fa?'کد ۶ رقمی':'6-digit code'}</span><input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required autoFocus value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} dir="ltr"/></label>}<button className="btn btnPrimary full" disabled={busy}>{busy?(fa?'لطفاً صبر کنید…':'Please wait…'):step==='email'?(fa?'ارسال کد':'Send code'):(fa?'تأیید و ادامه':'Verify and continue')}</button>{step==='otp'&&<button type="button" className="backLink" onClick={()=>setStep('email')}>{fa?'تغییر ایمیل':'Change email'}</button>}<a className="backLink" href={`/api/locale?lang=${fa?'en':'fa'}&next=/account`}>{fa?'English':'فارسی'}</a></form></section></main>;
}
