import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { db, ensureSchema } from '@/lib/db';
import { emailSettings } from '@/lib/schema';
import type { Locale } from '@/lib/i18n';

function secretKey(){return createHash('sha256').update(process.env.SESSION_SECRET||'').digest();}
export function encryptSecret(value:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',secretKey(),iv);const body=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);const tag=cipher.getAuthTag();return Buffer.concat([iv,tag,body]).toString('base64');}
export function decryptSecret(value:string){const raw=Buffer.from(value,'base64');const iv=raw.subarray(0,12),tag=raw.subarray(12,28),body=raw.subarray(28);const decipher=createDecipheriv('aes-256-gcm',secretKey(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(body),decipher.final()]).toString('utf8');}
async function settings(){await ensureSchema();const [row]=await db().select().from(emailSettings).limit(1);return row||null;}
function shell(title:string,body:string,locale:Locale){return `<!doctype html><html lang="${locale}" dir="${locale==='fa'?'rtl':'ltr'}"><body style="margin:0;background:#f4f5f7;font-family:Arial,Tahoma,sans-serif;color:#111827"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:40px 16px"><table width="100%" style="max-width:560px;background:#fff;border-radius:20px;padding:34px;box-shadow:0 10px 30px rgba(15,23,42,.08)"><tr><td><div style="font-size:12px;letter-spacing:.16em;color:#6b7280;text-transform:uppercase">PUBLIO · Powered by badje.ir</div><h1 style="font-size:26px;margin:14px 0 18px">${title}</h1>${body}<p style="margin-top:30px;color:#6b7280;font-size:13px">${locale==='fa'?'این ایمیل به‌صورت خودکار از Publio ارسال شده است.':'This message was sent automatically by Publio.'}</p></td></tr></table></td></tr></table></body></html>`;}
export async function sendMail(to:string,subject:string,html:string){const s=await settings();if(!s?.enabled||!s.apiKeyEncrypted)return false;const apiKey=decryptSecret(s.apiKeyEncrypted);const res=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:`${s.fromName} <${s.fromEmail}>`,to:[to],subject,html,reply_to:s.replyTo||undefined})});if(!res.ok){console.error('Resend failed',res.status,await res.text());return false;}return true;}
export async function sendOtpMail(email:string,code:string,locale:Locale){const subject=locale==='fa'?'کد تأیید Publio':'Your Publio verification code';const body=locale==='fa'?`<p>کد ورود/ثبت‌نام شما:</p><div style="font-size:38px;font-weight:800;letter-spacing:8px;text-align:center;padding:20px;background:#f3f4f6;border-radius:14px;direction:ltr">${code}</div><p>این کد تا ۱۰ دقیقه معتبر است.</p>`:`<p>Your sign-in / registration code is:</p><div style="font-size:38px;font-weight:800;letter-spacing:8px;text-align:center;padding:20px;background:#f3f4f6;border-radius:14px">${code}</div><p>This code expires in 10 minutes.</p>`;return sendMail(email,subject,shell(subject,body,locale));}
export async function sendWelcomeMail(email:string,locale:Locale){const subject=locale==='fa'?'حساب Publio شما آماده است':'Welcome to Publio';const body=locale==='fa'?'<p>ثبت‌نام شما با موفقیت انجام شد. پلن رایگان شما شامل ۵۰ مگابایت فضا است.</p>':'<p>Your account is ready. Your free plan includes 50 MB of storage.</p>';return sendMail(email,subject,shell(subject,body,locale));}
export async function sendAdminChangeMail(email:string,locale:Locale,messageEn:string,messageFa:string){const subject=locale==='fa'?'تغییر در حساب Publio':'Your Publio account was updated';return sendMail(email,subject,shell(subject,`<p>${locale==='fa'?messageFa:messageEn}</p>`,locale));}
export async function sendLimitMail(email:string,locale:Locale){const subject=locale==='fa'?'سقف فضای Publio':'Publio storage limit reached';const body=locale==='fa'?'<p>به سقف فضای پلن خود رسیده‌اید. برای افزایش فضا با publio@badje.ir تماس بگیرید.</p>':'<p>You reached your plan storage limit. Contact publio@badje.ir for more storage.</p>';return sendMail(email,subject,shell(subject,body,locale));}
